### ISSUE TITLE
TagBot failing

### ISSUE THREAD

**Issue by ReubenJ** [Herb-AI/HerbSearch.jl#103]
No clue what the cause might be at the moment, but interestingly, it looks to be different than https://github.com/Herb-AI/HerbGrammar.jl/issues/60.

<details><summary>Error output</summary>
<p>

```shell
/usr/bin/docker run --name xxxxxxxxxxxxxxxx --label xxxxxxxxxx --workdir /github/workspace --rm -e "INPUT_TOKEN" -e "INPUT_SSH" -e "INPUT_REGISTRY" -e "INPUT_GITHUB" -e "INPUT_GITHUB_API" -e "INPUT_BRANCHES" -e "INPUT_DISPATCH" -e "INPUT_DISPATCH_DELAY" -e "INPUT_LOOKBACK" -e "INPUT_SSH_PASSWORD" -e "INPUT_GPG" -e "INPUT_GPG_PASSWORD" -e "INPUT_REGISTRY_SSH" -e "INPUT_DRAFT" -e "INPUT_USER" -e "INPUT_EMAIL" -e "INPUT_BRANCH" -e "INPUT_SUBDIR" -e "INPUT_TAG_PREFIX" -e "INPUT_CHANGELOG" -e "INPUT_CHANGELOG_IGNORE" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/HerbSearch.jl/HerbSearch.jl":"/github/workspace" ghcr.io/juliaregistries/tagbot:1.18.1
Processing version v0.3.0 (24c3600a0237c7c2021f73518c0940f730fd5ee1)
Generating changelog for version v0.3.0 (24c3600a0237c7c2021f73518c0940f730fd5ee1)
{'server': 'GitHub.com', 'date': 'Wed, 15 May 2024 12:28:31 GMT', 'content-type': 'application/json; charset=utf-8', 'content-length': '116', 'x-github-media-type': 'github.v3; format=json', 'x-accepted-github-permissions': 'contents=write; contents=write,workflows=write', 'x-github-api-version-selected': '2022-11-28', 'x-ratelimit-limit': '5000', 'x-ratelimit-remaining': '4821', 'x-ratelimit-reset': '1715777414', 'x-ratelimit-used': '179', 'x-ratelimit-resource': 'core', 'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset', 'access-control-allow-origin': '*', 'strict-transport-security': 'max-age=31536000; includeSubdomains; preload', 'x-frame-options': 'deny', 'x-content-type-options': 'nosniff', 'x-xss-protection': '0', 'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin', 'content-security-policy': "default-src 'none'", 'vary': 'Accept-Encoding, Accept, X-Requested-With', 'x-github-request-id': 'xxxxxxxxxxxxxxxxxxxx'}
Error: TagBot experienced an unexpected internal failure
Traceback (most recent call last):
  File "/root/tagbot/action/__main__.py", line 96, in <module>
    repo.create_release(version, sha)
  File "/root/tagbot/action/repo.py", line 605, in create_release
    self._repo.create_git_ref(f"refs/tags/{version_tag}", tag.sha)
  File "/usr/local/lib/python3.8/site-packages/github/Repository.py", line 1023, in create_git_ref
    headers, data = self._requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 398, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 423, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {"message": "Reference update failed", "documentation_url": "https://docs.github.com/rest/git/refs#create-a-reference"}

Error: Issue reporting failed
Traceback (most recent call last):
  File "/root/tagbot/action/__main__.py", line 96, in <module>
    repo.create_release(version, sha)
  File "/root/tagbot/action/repo.py", line 605, in create_release
    self._repo.create_git_ref(f"refs/tags/{version_tag}", tag.sha)
  File "/usr/local/lib/python3.8/site-packages/github/Repository.py", line 1023, in create_git_ref
    headers, data = self._requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 398, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 423, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {"message": "Reference update failed", "documentation_url": "https://docs.github.com/rest/git/refs#create-a-reference"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/tagbot/action/__main__.py", line 99, in <module>
    repo.handle_error(e)
  File "/root/tagbot/action/repo.py", line 645, in handle_error
    raise Abort("Cannot continue due to internal failure")
tagbot.action.Abort: Cannot continue due to internal failure
Traceback (most recent call last):
  File "/root/tagbot/action/__main__.py", line 96, in <module>
    repo.create_release(version, sha)
  File "/root/tagbot/action/repo.py", line 605, in create_release
    self._repo.create_git_ref(f"refs/tags/{version_tag}", tag.sha)
  File "/usr/local/lib/python3.8/site-packages/github/Repository.py", line 1023, in create_git_ref
    headers, data = self._requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 398, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 423, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {"message": "Reference update failed", "documentation_url": "https://docs.github.com/rest/git/refs#create-a-reference"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/usr/local/lib/python3.8/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/usr/local/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
TypeError: request() got an unexpected keyword argument 'chunked'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/tagbot/action/repo.py", line 640, in handle_error
    self._report_error(trace)
  File "/root/tagbot/action/repo.py", line 442, in _report_error
    "image": self._image_id(),
  File "/root/tagbot/action/repo.py", line 431, in _image_id
    client = docker.from_env()
  File "/usr/local/lib/python3.8/site-packages/docker/client.py", line 96, in from_env
    return cls(
  File "/usr/local/lib/python3.8/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: request() got an unexpected keyword argument 'chunked'

```

</p>
</details>

**Comment by THinnerichs** [comment]
Is this still relevant?

**Comment by ReubenJ** [comment]
It's fixed for now. I believe @pwochner applied the same as in `HerbGrammar`: https://github.com/Herb-AI/HerbGrammar.jl/issues/91#issuecomment-2476325015
